# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ccyblog
email: 810278677@qq.com
description:  一个不务正业的游戏客户端开发者
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ccyblog.com" # the base hostname & protocol for your site
baseurl: ""
twitter_username: no
github_username:  isghost

# Build settings
markdown: kramdown
