title: isghost
description: 个人博客
show_downloads: false
google_analytics:
theme:
url: "http://www.ccyblog.com" 
email: 810278677@qq.com

# Build settings
markdown: kramdown

# gems: [jekyll-paginate]
# paginate: 5
# paginate_path: "page:num"
